theme: jekyll-theme-slate
exclude: ["README.md"]

title : snormax.github.io
description : A simple site for my extracurricular projects
production_url : https://snormax.github.io/
author :
  name : snormax
  email : snormax@users.noreply.github.com
  github : snormax
  feedburner : nil

show_downloads : false
