permalink: /:categories/:year/:month/:day/:title

theme: jekyll-theme-slate
exclude: ["README.md"]
hightlighter: rouge

title : snormax.github.io
tagline : test6
author :
  name : snormax
  email : snormax@users.noreply.github.com
  github : snormax
  feedburner : nil

production_url : https://snormax.github.io/
